apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: payment-service
  annotations:
    autoscaling.knative.dev/min-scale: "1"
  labels:
    app.kubernetes.io/part-of: payment-service
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  source:
    git:
      url: https://github.com/tsalm-vmware/payment-service.git
      ref:
        branch: main
  serviceClaims:
  - name: config-server
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: configserver-binding-compatible
  - name: observability
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: observability-binding-compatible